"""
Support domain — create (input) schemas.
"""

from __future__ import annotations

import uuid
from typing import Annotated

from pydantic import Field, field_validator

from app.models.enums import TicketCategory, TicketPriority
from app.schemas.base import BaseSchema

__all__ = [
    "SupportTicketCreate",
    "SupportMessageCreate",
    "SupportAttachmentCreate",
]


class SupportTicketCreate(BaseSchema):
    """
    Customer-facing input for opening a new support ticket.

    ticket_number is generated by the service layer (not supplied by the client).
    priority defaults to MEDIUM; agents may escalate after initial triage.
    The owning customer is always the authenticated caller (injected server-side
    from the auth token) — never accepted from the request body, both because
    the client has no legitimate reason to open a ticket "as" another user and
    because the mobile app never sends this field.
    """

    category: TicketCategory = Field(
        description="Ticket classification used for routing to the correct agent queue.",
    )
    subject: str = Field(
        max_length=300,
        description="Short summary of the issue (shown in ticket list views).",
    )
    description: str = Field(
        min_length=20,
        description="Detailed description of the issue provided by the customer.",
    )
    booking_id: uuid.UUID | None = Field(
        default=None,
        description="Related booking UUID, if the issue is booking-specific.",
    )
    payment_id: uuid.UUID | None = Field(
        default=None,
        description="Related payment UUID, if the issue is payment-specific.",
    )
    priority: TicketPriority = Field(
        default=TicketPriority.MEDIUM,
        description="Initial priority. Agents may escalate or downgrade after triage.",
    )

    @field_validator("subject", "description")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        return v.strip()


class SupportMessageCreate(BaseSchema):
    """
    Input for adding a message to an existing support ticket thread.

    The sender is always the authenticated caller (injected server-side from
    the auth token, like SupportTicketCreate.customer_id) — never accepted
    from the request body. message_type is derived server-side from the
    sender's role, not supplied by the client.

    is_internal messages are agent notes not visible to the customer.
    The router should enforce that only agents can set is_internal=True.
    """

    body: str = Field(
        min_length=1,
        description="Message body text. Markdown is supported in agent replies.",
    )
    is_internal: bool = Field(
        default=False,
        description="Agent-only note. Must be False for all customer-originated messages.",
    )


class SupportAttachmentCreate(BaseSchema):
    """
    Input for associating an uploaded file with a ticket or message.

    File upload itself is handled by the media service. This schema records
    the resulting file metadata for the support context.
    """

    ticket_id: uuid.UUID = Field(description="Parent ticket UUID.")
    message_id: uuid.UUID | None = Field(
        default=None,
        description="Associated message UUID. None means the attachment is at ticket level.",
    )
    uploaded_by_id: uuid.UUID = Field(description="UUID of the user who uploaded the file.")
    file_name: str = Field(
        max_length=300,
        description="Original filename as provided by the uploader.",
    )
    file_url: str = Field(
        max_length=2048,
        description="CDN or storage URL of the uploaded file.",
    )
    file_type: str = Field(
        max_length=100,
        description="MIME type, e.g. 'image/jpeg', 'application/pdf'.",
    )
    file_size_bytes: int | None = Field(
        default=None,
        ge=0,
        description="File size in bytes. Used for storage quota enforcement.",
    )
