"""
Referrals domain — create (request body) schemas.

Used by POST endpoints to create new Referral and ReferralReward records.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal

from pydantic import Field, field_validator

from app.schemas.base import BaseSchema, MoneyAmount
from app.schemas.referrals.common import (
    Currency,
    ReferralChannel,
    ReferralRewardTrigger,
    RewardType,
)


class ReferralCreate(BaseSchema):
    """
    Payload for recording a new outbound referral.

    Created when a referrer shares their code and the platform captures
    the event (e.g., on link click with IP capture, or on WhatsApp share).
    """

    referrer_id: uuid.UUID = Field(description="User ID of the person who referred")
    referral_code: str = Field(
        min_length=3,
        max_length=20,
        description="The referral code that was shared or used",
    )
    channel: ReferralChannel = Field(
        default=ReferralChannel.LINK,
        description="Channel through which the referral was initiated",
    )
    ip_address: str | None = Field(
        default=None,
        max_length=45,
        description="IP address of the referral click (IPv4 or IPv6)",
    )

    @field_validator("referral_code")
    @classmethod
    def strip_and_upper_code(cls, v: str) -> str:
        """Normalise referral code to uppercase, trimmed."""
        return v.strip().upper()


class ReferralRewardCreate(BaseSchema):
    """
    Payload for creating a referral reward record.

    Generated by the referral service when a trigger event occurs
    (signup, first booking, etc.). wallet_id is resolved by the service.
    """

    referral_id: uuid.UUID = Field(description="ID of the parent Referral")
    recipient_id: uuid.UUID = Field(
        description="User ID of the reward recipient (referrer or referred user)"
    )
    reward_trigger: ReferralRewardTrigger = Field(
        description="Business event that triggered this reward"
    )
    reward_type: RewardType = Field(description="Category of reward being issued")
    amount: MoneyAmount = Field(description="Monetary value of the reward")
    currency: Currency = Field(description="ISO 4217 currency code for the reward")
    wallet_id: uuid.UUID | None = Field(
        default=None,
        description="Wallet to credit; resolved by service if omitted",
    )
    expires_at: datetime | None = Field(
        default=None,
        description="Optional expiry date after which the reward lapses",
    )
    notes: str | None = Field(
        default=None,
        max_length=1000,
        description="Internal notes for support or audit purposes",
    )


class ReferralApplyCreate(BaseSchema):
    """User: apply a referral code at registration or first booking."""

    referral_code: str = Field(
        min_length=4,
        max_length=20,
        description="Referral code shared by the referrer.",
    )
    referred_user_id: uuid.UUID = Field(
        description="User ID of the person applying the code (the new user).",
    )
    channel: ReferralChannel = Field(
        default=ReferralChannel.LINK,
        description="Channel through which the referral code was shared.",
    )

    @field_validator("referral_code")
    @classmethod
    def normalise_code(cls, v: str) -> str:
        return v.strip().upper()
