"""
Auth domain — common annotated types, nested helpers, and enum re-exports.

Import from here rather than directly from app.models.enums so that
auth schema modules have a single, stable import surface.
"""

from __future__ import annotations

import re
import uuid
from datetime import datetime
from typing import Annotated

from pydantic import Field, field_validator

from app.models.enums import (
    DeviceType,
    LoginMethod,
    OTPDeliveryChannel,
    OTPPurpose,
    OTPStatus,
    Platform,
    SessionStatus,
    TokenRevocationReason,
)
from app.schemas.base import BaseSchema, PhoneNumber

# ── Re-export enums for auth consumers ────────────────────────────────────────

__all__ = [
    # Enums
    "OTPDeliveryChannel",
    "OTPPurpose",
    "OTPStatus",
    "SessionStatus",
    "LoginMethod",
    "DeviceType",
    "Platform",
    "TokenRevocationReason",
    # Annotated types
    "OTPIdentifier",
    "OTPCode",
    # Nested schemas
    "DeviceInfoSchema",
    "LocationInfoSchema",
]

# ── Regex helpers ──────────────────────────────────────────────────────────────

_PHONE_RE = re.compile(r"^\+[1-9]\d{9,14}$")
_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

# ── Annotated scalar types ─────────────────────────────────────────────────────

OTPIdentifier = Annotated[
    str,
    Field(
        min_length=5,
        max_length=320,
        description=(
            "Phone number (E.164, e.g. +919876543210) "
            "or email address used to receive the OTP."
        ),
    ),
]
"""
Polymorphic identifier: accepts either a valid E.164 phone number or
an RFC-5322 email address. Validated at the schema layer via
`validate_otp_identifier`.
"""

OTPCode = Annotated[
    str,
    Field(
        min_length=4,
        max_length=8,
        pattern=r"^\d{4,8}$",
        description="Numeric OTP code submitted by the user (4–8 digits).",
    ),
]
"""Raw OTP string submitted by the end-user for verification."""


def validate_otp_identifier(value: str) -> str:
    """
    Ensure `value` is either a valid E.164 phone number or an email address.

    Raises ValueError on invalid input so Pydantic surfaces a clean 422.
    """
    stripped = value.strip()
    if _PHONE_RE.match(stripped) or _EMAIL_RE.match(stripped):
        return stripped
    raise ValueError(
        "identifier must be a valid E.164 phone number (e.g. +919876543210) "
        "or an email address."
    )


# ── Nested helper schemas ──────────────────────────────────────────────────────


class DeviceInfoSchema(BaseSchema):
    """
    Device context attached to a session or OTP request.

    All fields are optional because some platforms (e.g. web) may not
    supply the full device fingerprint.
    """

    device_id: str | None = Field(
        default=None,
        max_length=256,
        description="Stable device identifier generated by the client SDK.",
    )
    device_name: str | None = Field(
        default=None,
        max_length=200,
        description="Human-readable device name (e.g. 'iPhone 15 Pro').",
    )
    device_type: DeviceType | None = Field(
        default=None,
        description="Physical form factor of the client device.",
    )
    platform: Platform | None = Field(
        default=None,
        description="OS platform of the client device.",
    )
    os: str | None = Field(default=None, max_length=50)
    os_version: str | None = Field(default=None, max_length=50)
    browser: str | None = Field(default=None, max_length=100)
    browser_version: str | None = Field(default=None, max_length=100)
    app_version: str | None = Field(default=None, max_length=50)
    user_agent: str | None = Field(default=None, max_length=512)


class LocationInfoSchema(BaseSchema):
    """
    Geo-location context derived from IP or GPS for session records.

    This is informational only; never used for access-control decisions.
    """

    ip_address: str | None = Field(default=None, max_length=45)
    country_code: str | None = Field(default=None, max_length=2)
    region: str | None = Field(default=None, max_length=100)
    city: str | None = Field(default=None, max_length=100)
    timezone: str | None = Field(default=None, max_length=64)
    language: str | None = Field(default=None, max_length=20)
