"""
BookingInvoice — GST-compliant invoice snapshot for a booking.

Captures all billing details at invoice generation time (immutable snapshot).
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Index,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base
from app.models.enums import InvoiceStatus
from app.models.mixins import TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.bookings.booking import Booking


class BookingInvoice(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """
    A GST-compliant invoice for a booking.

    Invoices are point-in-time snapshots of the booking financials.
    Multiple invoices can exist per booking (e.g., original + revised after amendment).
    Only one invoice should have `is_current=True` at any time.

    Billing details (name, address, GST number) are copied from the customer
    profile at generation time — changes to the profile do NOT affect existing invoices.

    `tax_breakdown` JSONB structure:
        {
          "cgst_pct": 9.0,   "cgst_amount": 900.0,
          "sgst_pct": 9.0,   "sgst_amount": 900.0,
          "igst_pct": 0.0,   "igst_amount": 0.0,
          "total_tax": 1800.0
        }
    CGST+SGST applies for intra-state; IGST applies for inter-state (B2B).
    """

    __tablename__ = "booking_invoices"

    __table_args__ = (
        UniqueConstraint("invoice_number", name="uq_booking_invoices_invoice_number"),
        Index("ix_booking_invoices_booking_id", "booking_id"),
        Index("ix_booking_invoices_current", "booking_id", "is_current"),
        CheckConstraint("subtotal >= 0", name="ck_booking_invoice_subtotal_non_negative"),
        CheckConstraint("total_amount >= 0", name="ck_booking_invoice_total_non_negative"),
    )

    # ── Ownership ─────────────────────────────────────────────────────────────

    booking_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("bookings.id", ondelete="RESTRICT"),
        nullable=False,
    )

    # ── Invoice Identity ──────────────────────────────────────────────────────

    invoice_number: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        unique=True,
        comment="Sequential invoice reference e.g. INV-2024-001234. Generated by service layer.",
    )

    invoice_status: Mapped[InvoiceStatus] = mapped_column(
        SAEnum(InvoiceStatus, name="invoice_status", native_enum=False),
        nullable=False,
    )

    is_current: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        comment="True for the latest valid invoice. False for superseded versions.",
    )

    invoice_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        comment="Date printed on the invoice (may differ from created_at for backdated invoices)",
    )

    # ── Billing Details (snapshot at generation time) ─────────────────────────

    billing_name: Mapped[str] = mapped_column(String(300), nullable=False)

    billing_address: Mapped[str] = mapped_column(Text, nullable=False)

    billing_city: Mapped[str | None] = mapped_column(String(100), nullable=True)

    billing_state: Mapped[str | None] = mapped_column(String(100), nullable=True)

    billing_pincode: Mapped[str | None] = mapped_column(String(10), nullable=True)

    billing_gstin: Mapped[str | None] = mapped_column(
        String(15),
        nullable=True,
        comment="Customer's GST number if applicable (for B2B invoices)",
    )

    billing_pan: Mapped[str | None] = mapped_column(String(10), nullable=True)

    # ── Tyohaar Billing ───────────────────────────────────────────────────────

    tyohaar_gstin: Mapped[str | None] = mapped_column(
        String(15),
        nullable=True,
        comment="Tyohaar's GST number for the jurisdiction of this invoice",
    )

    # ── Financials ────────────────────────────────────────────────────────────

    subtotal: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)

    discount_amount: Mapped[Decimal] = mapped_column(
        Numeric(12, 2), nullable=False, default=Decimal("0.00")
    )

    taxable_amount: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        nullable=False,
        comment="subtotal − discount_amount (tax is calculated on this)",
    )

    tax_amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)

    platform_fee: Mapped[Decimal] = mapped_column(
        Numeric(12, 2), nullable=False, default=Decimal("0.00")
    )

    total_amount: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        nullable=False,
        comment="taxable_amount + tax_amount + platform_fee",
    )

    # ── Tax Breakdown ─────────────────────────────────────────────────────────

    tax_breakdown: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment=(
            "GST breakdown: "
            "{cgst_pct, cgst_amount, sgst_pct, sgst_amount, igst_pct, igst_amount, total_tax}"
        ),
    )

    # ── Document ──────────────────────────────────────────────────────────────

    invoice_url: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
        comment="CDN URL of the generated PDF invoice",
    )

    generated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="When the PDF was generated and uploaded",
    )

    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Relationships ─────────────────────────────────────────────────────────

    booking: Mapped[Booking] = relationship(
        "Booking",
        back_populates="invoices",
        lazy="noload",
    )

    def __repr__(self) -> str:
        return (
            f"<BookingInvoice id={self.id} number={self.invoice_number!r} "
            f"total={self.total_amount} current={self.is_current}>"
        )
