"""
Booking — the operational core of the Tyohaar business.

Every booking references a customer, a celebration, and a selected package.
Vendor assignments are internal; customers never see them.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime, time
from decimal import Decimal
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Index,
    Numeric,
    String,
    Text,
    Time,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base
from app.models.enums import (
    BalloonColorMode,
    BookingStatus,
    BookingType,
    CancellationReason,
    Currency,
    PaymentStatus,
)
from app.models.mixins import (
    MetadataMixin,
    NotesMixin,
    SoftDeleteMixin,
    TimestampMixin,
    UUIDPrimaryKeyMixin,
)

if TYPE_CHECKING:
    from app.models.users.user import User
    from app.models.users.address import UserAddress
    from app.models.occasions.celebration import Celebration
    from app.models.packages.package import Package
    from app.models.bookings.booking_item import BookingItem
    from app.models.bookings.booking_assignment import BookingAssignment
    from app.models.bookings.booking_status_history import BookingStatusHistory
    from app.models.bookings.booking_cancellation import BookingCancellation
    from app.models.bookings.booking_reschedule import BookingReschedule
    from app.models.bookings.booking_invoice import BookingInvoice
    from app.models.payments.payment import Payment


class Booking(UUIDPrimaryKeyMixin, TimestampMixin, SoftDeleteMixin, NotesMixin, MetadataMixin, Base):
    """
    A confirmed service engagement between Tyohaar and a customer.

    A Booking is created when a customer selects a Package for their Celebration
    and proceeds to checkout. It drives:
    - Internal vendor assignment (via BookingItem → BookingAssignment)
    - Payment collection and settlement
    - Service execution tracking
    - GST-compliant invoicing

    Customers interact with bookings through the status, timeline, and financials.
    Vendor details (BookingAssignment) are NEVER exposed to customers.

    Financial fields (all Numeric(12, 2), in `currency`):
    - `subtotal`:       Sum of all item final_prices
    - `discount_amount`: Platform/coupon discounts applied
    - `tax_amount`:     GST on (subtotal − discount_amount)
    - `platform_fee`:  Flat Tyohaar service fee
    - `total_amount`:  subtotal − discount_amount + tax_amount + platform_fee
    - `amount_paid`:   Cumulative confirmed payments received
    - `amount_due`:    total_amount − amount_paid

    All financial fields are kept in sync by the service layer.
    `booking_number` is a human-readable reference (e.g., TYH-20240615-001234)
    generated by the service layer before insert.
    """

    __tablename__ = "bookings"

    __table_args__ = (
        UniqueConstraint("booking_number", name="uq_bookings_booking_number"),
        Index("ix_bookings_customer_id", "customer_id"),
        Index("ix_bookings_celebration_id", "celebration_id"),
        Index("ix_bookings_package_id", "package_id"),
        Index("ix_bookings_booking_status", "booking_status"),
        Index("ix_bookings_payment_status", "payment_status"),
        Index("ix_bookings_scheduled_date", "scheduled_date"),
        Index("ix_bookings_customer_status", "customer_id", "booking_status"),
        CheckConstraint("subtotal >= 0", name="ck_booking_subtotal_non_negative"),
        CheckConstraint("discount_amount >= 0", name="ck_booking_discount_non_negative"),
        CheckConstraint("tax_amount >= 0", name="ck_booking_tax_non_negative"),
        CheckConstraint("platform_fee >= 0", name="ck_booking_platform_fee_non_negative"),
        CheckConstraint("total_amount >= 0", name="ck_booking_total_non_negative"),
        CheckConstraint("amount_paid >= 0", name="ck_booking_amount_paid_non_negative"),
        CheckConstraint("amount_due >= 0", name="ck_booking_amount_due_non_negative"),
    )

    # ── Human-Readable Reference ──────────────────────────────────────────────

    booking_number: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        unique=True,
        comment="Human-readable reference e.g. TYH-20240615-001234. Generated by service layer.",
    )

    # ── Core References ───────────────────────────────────────────────────────

    customer_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )

    celebration_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("celebrations.id", ondelete="RESTRICT"),
        nullable=False,
        comment="The celebration this booking is for",
    )

    package_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("packages.id", ondelete="RESTRICT"),
        nullable=False,
        comment="The package selected by the customer",
    )

    address_id: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("user_addresses.id", ondelete="SET NULL"),
        nullable=True,
        comment="Service delivery address. May differ from celebration venue.",
    )

    recipient_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    recipient_phone: Mapped[str | None] = mapped_column(String(20), nullable=True)

    # ── Scheduling ────────────────────────────────────────────────────────────

    scheduled_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        comment="Date on which service delivery is scheduled",
    )

    scheduled_start_time: Mapped[time | None] = mapped_column(
        Time(timezone=False),
        nullable=True,
    )

    scheduled_end_time: Mapped[time | None] = mapped_column(
        Time(timezone=False),
        nullable=True,
    )

    # ── Type & Status ─────────────────────────────────────────────────────────

    booking_type: Mapped[BookingType] = mapped_column(
        SAEnum(BookingType, name="booking_type", native_enum=False),
        nullable=False,
    )

    booking_status: Mapped[BookingStatus] = mapped_column(
        SAEnum(BookingStatus, name="booking_status", native_enum=False),
        nullable=False,
        index=True,
    )

    payment_status: Mapped[PaymentStatus] = mapped_column(
        SAEnum(PaymentStatus, name="payment_status", native_enum=False),
        nullable=False,
        comment="Denormalized from Payment records. Updated by service layer on payment events.",
    )

    # ── Financials ────────────────────────────────────────────────────────────

    currency: Mapped[Currency] = mapped_column(
        SAEnum(Currency, name="currency", native_enum=False),
        nullable=False,
        default=Currency.INR,
    )

    subtotal: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        nullable=False,
        default=Decimal("0.00"),
        comment="Sum of all BookingItem.final_price values",
    )

    discount_amount: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        nullable=False,
        default=Decimal("0.00"),
        comment="Total discount applied (coupon + promotional)",
    )

    applied_coupon_ids: Mapped[list[str] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment=(
            "UUID strings of the Coupon(s) evaluated and locked into "
            "discount_amount at booking-creation time by DiscountEngine. "
            "Redeemed (CouponRedemption rows + times_used increment) once "
            "payment is confirmed — see DiscountEngine.record_usage."
        ),
    )

    tax_amount: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        nullable=False,
        default=Decimal("0.00"),
        comment="GST on (subtotal − discount_amount)",
    )

    platform_fee: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        nullable=False,
        default=Decimal("0.00"),
        comment="Flat Tyohaar service fee",
    )

    total_amount: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        nullable=False,
        default=Decimal("0.00"),
        comment="subtotal − discount + tax + platform_fee. Authoritative charge to customer.",
    )

    amount_paid: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        nullable=False,
        default=Decimal("0.00"),
        comment="Cumulative confirmed payments received. Updated on payment capture.",
    )

    amount_due: Mapped[Decimal] = mapped_column(
        Numeric(12, 2),
        nullable=False,
        default=Decimal("0.00"),
        comment="total_amount − amount_paid. Updated by service layer.",
    )

    preparation_start_time: Mapped[time | None] = mapped_column(
        Time,
        nullable=True,
        comment="Preparation Starting Time [PST] provided by the vendor "
                "(legacy time-only mirror of preparation_start_at)",
    )

    preparation_start_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Full date + time at which the vendor will arrive/start "
                "preparation at the customer's event location (PST)",
    )

    # ── Important Timestamps ──────────────────────────────────────────────────

    confirmed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="When the booking transitioned to CONFIRMED status",
    )

    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="When the booking transitioned to COMPLETED status",
    )

    # ── Instructions & Reason ─────────────────────────────────────────────────

    special_instructions: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Customer's special requests (visible to Tyohaar coordinators, not vendors)",
    )

    customization_note: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Customer's free-form custom requirements typed in the plan-flow "
                "Details step, distinct from special_instructions. Visible to both "
                "the vendor and Tyohaar admin.",
    )

    balloon_color_mode: Mapped[BalloonColorMode | None] = mapped_column(
        SAEnum(BalloonColorMode, name="balloon_color_mode", native_enum=False),
        nullable=True,
        comment="Customer's chosen balloon décor style: a single accent colour or a two-colour combination.",
    )

    balloon_colors: Mapped[list[str] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment=(
            "Hex codes of the chosen balloon colour(s) — 1 item for SINGLE mode, "
            "2 for DUAL. Values are drawn from app.core.constants.BALLOON_COLOR_PALETTE."
        ),
    )

    cancellation_reason: Mapped[CancellationReason | None] = mapped_column(
        SAEnum(CancellationReason, name="cancellation_reason", native_enum=False),
        nullable=True,
        comment="Set when booking_status = CANCELLED. Denormalized from BookingCancellation.",
    )

    # ── Relationships ─────────────────────────────────────────────────────────

    customer: Mapped[User] = relationship(
        "User",
        foreign_keys=[customer_id],
        lazy="noload",
    )

    celebration: Mapped[Celebration] = relationship("Celebration", lazy="noload")

    package: Mapped[Package] = relationship("Package", lazy="noload")

    address: Mapped[UserAddress | None] = relationship("UserAddress", lazy="noload")

    items: Mapped[list[BookingItem]] = relationship(
        "BookingItem",
        back_populates="booking",
        lazy="noload",
        cascade="all, delete-orphan",
    )

    status_history: Mapped[list[BookingStatusHistory]] = relationship(
        "BookingStatusHistory",
        back_populates="booking",
        lazy="noload",
        cascade="all, delete-orphan",
    )

    cancellation: Mapped[BookingCancellation | None] = relationship(
        "BookingCancellation",
        back_populates="booking",
        uselist=False,
        lazy="noload",
    )

    reschedules: Mapped[list[BookingReschedule]] = relationship(
        "BookingReschedule",
        back_populates="booking",
        lazy="noload",
        cascade="all, delete-orphan",
    )

    invoices: Mapped[list[BookingInvoice]] = relationship(
        "BookingInvoice",
        back_populates="booking",
        lazy="noload",
    )

    payments: Mapped[list[Payment]] = relationship(
        "Payment",
        back_populates="booking",
        lazy="noload",
    )

    @property
    def is_cancellable(self) -> bool:
        return self.booking_status not in (
            BookingStatus.COMPLETED,
            BookingStatus.CANCELLED,
        )

    def __repr__(self) -> str:
        return (
            f"<Booking id={self.id} number={self.booking_number!r} "
            f"status={self.booking_status} total={self.total_amount}>"
        )
