"""
Invitation — a digital event invitation card created by a customer for their celebration.

Customers design invitations using templates, populate event details, and share
them with guests via WhatsApp, SMS, email, or a shareable link. Supports RSVP
collection, QR-code-based check-in, and multi-channel delivery tracking.
"""

from __future__ import annotations

import enum
import uuid
from datetime import date, datetime, time
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    Time,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base
from app.models.enums import InvitationStatus, Language
from app.models.mixins import MetadataMixin, SoftDeleteMixin, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.occasions.celebration import Celebration
    from app.models.users.user import User
    from app.models.invitations.invitation_template import InvitationTemplate
    from app.models.invitations.invitation_guest import InvitationGuest


class InvitationShareChannel(str, enum.Enum):
    """
    Channel through which an invitation is shared with guests.
    NOTE: Move to app/models/enums.py in the next enums update.
    """
    WHATSAPP = "whatsapp"
    SMS = "sms"
    EMAIL = "email"
    LINK = "link"                   # Shareable URL (can be shared anywhere)
    IN_APP = "in_app"               # Shared via the Tyohaar app's contact list


class Invitation(UUIDPrimaryKeyMixin, TimestampMixin, SoftDeleteMixin, MetadataMixin, Base):
    """
    A digital invitation for a celebration event.

    An Invitation is created by the celebration owner (customer) and shared
    with guests. It captures the event details, branding from the chosen
    template, RSVP configuration, and delivery state.

    Lifecycle:
    1. Customer creates invitation (status=DRAFT).
    2. Customer customizes using a template; populates event details.
    3. Customer sends invitation → status=SENT, sent_at set.
    4. At least one guest views the invitation → status=VIEWED.
    5. RSVP deadline passes or customer expires it → status=EXPIRED.

    `invitation_number` is a human-readable identifier (e.g., INV-2024-AB1234).
    `qr_token` is a unique token used to generate QR codes for event check-in.
    `share_url` is the canonical public URL for the invitation card.

    `placeholder_values` JSONB stores the filled template placeholders:
        {
          "host_name": "Priya & Arjun",
          "venue_map_url": "https://maps.google.com/...",
          "dress_code": "Ethnic wear",
          "custom_message": "Looking forward to celebrating with you!"
        }

    Guest counts are denormalized for fast reads and kept in sync by the service
    layer on every RSVP or guest-list change.
    """

    __tablename__ = "invitations"

    __table_args__ = (
        UniqueConstraint("invitation_number", name="uq_invitations_invitation_number"),
        UniqueConstraint("qr_token", name="uq_invitations_qr_token"),
        Index("ix_invitations_celebration_id", "celebration_id"),
        Index("ix_invitations_owner_id", "owner_id"),
        Index("ix_invitations_status", "invitation_status"),
        Index("ix_invitations_rsvp_deadline", "rsvp_deadline_at"),
        CheckConstraint(
            "total_guests_invited >= 0",
            name="ck_invitations_guests_invited_non_negative",
        ),
        CheckConstraint(
            "total_rsvp_attending >= 0",
            name="ck_invitations_rsvp_attending_non_negative",
        ),
        CheckConstraint(
            "total_rsvp_declined >= 0",
            name="ck_invitations_rsvp_declined_non_negative",
        ),
        CheckConstraint(
            "max_plus_ones >= 0",
            name="ck_invitations_max_plus_ones_non_negative",
        ),
    )

    # ── Identity ──────────────────────────────────────────────────────────────

    invitation_number: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        unique=True,
        comment="Human-readable reference e.g. INV-2024-AB1234. Generated by service layer.",
    )

    # ── Ownership ─────────────────────────────────────────────────────────────

    celebration_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("celebrations.id", ondelete="RESTRICT"),
        nullable=False,
        comment="The celebration this invitation is for.",
    )

    owner_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        comment="The customer who created and owns this invitation.",
    )

    template_id: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("invitation_templates.id", ondelete="SET NULL"),
        nullable=True,
        comment="The design template applied to this invitation. NULL for blank invitations.",
    )

    # ── Event Details ─────────────────────────────────────────────────────────

    title: Mapped[str] = mapped_column(
        String(300),
        nullable=False,
        comment="Invitation headline e.g. 'Priya & Arjun's Wedding Celebration'.",
    )

    personal_message: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Custom message from the host to guests, shown on the invitation card.",
    )

    event_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        comment="Primary date of the celebration event.",
    )

    event_start_time: Mapped[time | None] = mapped_column(
        Time(timezone=False),
        nullable=True,
    )

    event_end_time: Mapped[time | None] = mapped_column(
        Time(timezone=False),
        nullable=True,
    )

    venue_name: Mapped[str | None] = mapped_column(
        String(300),
        nullable=True,
        comment="Name of the event venue.",
    )

    venue_address: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Full venue address shown on the invitation.",
    )

    venue_map_url: Mapped[str | None] = mapped_column(
        String(1000),
        nullable=True,
        comment="Google Maps or similar link to the venue location.",
    )

    dress_code: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
        comment="Dress code instruction for guests e.g. 'Traditional Indian Attire'.",
    )

    # ── Status & Lifecycle ────────────────────────────────────────────────────

    invitation_status: Mapped[InvitationStatus] = mapped_column(
        SAEnum(InvitationStatus, name="invitation_status", native_enum=False),
        nullable=False,
        default=InvitationStatus.DRAFT,
    )

    language: Mapped[Language] = mapped_column(
        SAEnum(Language, name="language", native_enum=False),
        nullable=False,
        default=Language.ENGLISH,
        comment="Language in which the invitation is composed.",
    )

    # ── RSVP Configuration ────────────────────────────────────────────────────

    rsvp_enabled: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        comment="Whether RSVP collection is active for this invitation.",
    )

    rsvp_deadline_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Guests must respond by this timestamp. NULL means no deadline.",
    )

    max_plus_ones: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        comment="Maximum additional guests allowed per invitee globally.",
    )

    # ── Delivery ──────────────────────────────────────────────────────────────

    enabled_channels: Mapped[list[str] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="List of InvitationShareChannel values enabled for this invitation.",
    )

    share_url: Mapped[str | None] = mapped_column(
        String(1000),
        nullable=True,
        comment="Public URL for the invitation card page.",
    )

    # ── QR Code (future-ready) ────────────────────────────────────────────────

    qr_token: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        unique=True,
        comment=(
            "Unique token embedded in the event QR code. "
            "Used for guest check-in scanning. Generated on first send."
        ),
    )

    qr_code_url: Mapped[str | None] = mapped_column(
        String(1000),
        nullable=True,
        comment="CDN URL of the generated QR code image for event check-in.",
    )

    # ── Guest Count Summary (denormalized) ────────────────────────────────────

    total_guests_invited: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        comment="Total number of InvitationGuest records. Kept in sync by service layer.",
    )

    total_rsvp_attending: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        comment="Count of guests with rsvp_status=ATTENDING.",
    )

    total_rsvp_declined: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        comment="Count of guests with rsvp_status=DECLINED.",
    )

    # ── Key Timestamps ────────────────────────────────────────────────────────

    sent_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="When the invitation transitioned to SENT status.",
    )

    first_viewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="When the first guest viewed the invitation (status→VIEWED).",
    )

    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="When the invitation link expires. NULL means it never expires.",
    )

    # ── Template Customisation ────────────────────────────────────────────────

    cover_image_url: Mapped[str | None] = mapped_column(
        String(1000),
        nullable=True,
        comment="Custom or template-derived cover image URL for the invitation card.",
    )

    placeholder_values: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment=(
            "Map of template placeholder keys → customer-provided values. "
            "Merged with template HTML on render. Example: {host_name: 'Priya & Arjun'}."
        ),
    )

    # ── Relationships ─────────────────────────────────────────────────────────

    celebration: Mapped[Celebration] = relationship(
        "Celebration",
        lazy="noload",
    )

    owner: Mapped[User] = relationship(
        "User",
        lazy="noload",
    )

    template: Mapped[InvitationTemplate | None] = relationship(
        "InvitationTemplate",
        lazy="noload",
    )

    guests: Mapped[list[InvitationGuest]] = relationship(
        "InvitationGuest",
        back_populates="invitation",
        cascade="all, delete-orphan",
        lazy="noload",
    )

    @property
    def is_active(self) -> bool:
        return self.invitation_status not in (InvitationStatus.EXPIRED,)

    @property
    def rsvp_pending_count(self) -> int:
        return self.total_guests_invited - self.total_rsvp_attending - self.total_rsvp_declined

    def __repr__(self) -> str:
        return (
            f"<Invitation id={self.id} number={self.invitation_number!r} "
            f"status={self.invitation_status} guests={self.total_guests_invited}>"
        )
