"""
Media domain — update (patch) schemas.

All fields are Optional for partial PATCH semantics.
Core identity fields (owner_type, owner_id, url, usage) are immutable after creation.
"""

from __future__ import annotations

from datetime import date

from pydantic import Field

from app.models.enums import MediaStatus
from app.schemas.base import BaseSchema
from app.schemas.media.common import (
    MemoryVisibility,
    ModerationStatus,
    VideoTranscodingStatus,
)

__all__ = [
    "ImageUpdate",
    "VideoUpdate",
    "MemoryUpdate",
]


class ImageUpdate(BaseSchema):
    """
    Partial update schema for Image records.

    Only post-processing and display fields are patchable.
    url and owner fields are immutable.
    """

    thumbnail_url: str | None = Field(
        default=None,
        max_length=2048,
        description="Updated thumbnail URL after processing pipeline completes.",
    )
    alt_text: str | None = Field(
        default=None,
        max_length=500,
        description="Updated accessibility alt text.",
    )
    display_order: int | None = Field(
        default=None,
        ge=0,
        description="Updated sort position within the gallery.",
    )
    is_primary: bool | None = Field(
        default=None,
        description="Promote or demote this image as the primary/featured asset.",
    )
    status: MediaStatus | None = Field(
        default=None,
        description="Updated media lifecycle status.",
    )
    moderation_status: ModerationStatus | None = Field(
        default=None,
        description="Admin-only: updated moderation decision.",
    )


class VideoUpdate(BaseSchema):
    """
    Partial update schema for Video records.

    Used by the transcoding pipeline to record completion state and
    by users/admins to update display metadata.
    """

    thumbnail_url: str | None = Field(
        default=None,
        max_length=2048,
        description="Thumbnail URL extracted during transcoding.",
    )
    processed_url: str | None = Field(
        default=None,
        max_length=2048,
        description="CDN URL of the transcoded/optimised video.",
    )
    transcoding_status: VideoTranscodingStatus | None = Field(
        default=None,
        description="Updated transcoding pipeline state.",
    )
    title: str | None = Field(default=None, max_length=300)
    description: str | None = Field(default=None, max_length=2000)
    status: MediaStatus | None = Field(
        default=None,
        description="Updated media lifecycle status.",
    )
    is_primary: bool | None = None


# Alias consumed by the media controller
ImageMetadataUpdate = ImageUpdate


class MemoryUpdate(BaseSchema):
    """
    Partial update schema for Memory album records.

    share_token is not patchable here — it is generated by the dedicated
    share endpoint and cleared by the revoke endpoint.
    """

    title: str | None = Field(default=None, max_length=300, min_length=1)
    description: str | None = None
    visibility: MemoryVisibility | None = None
    memory_date: date | None = None
    location: str | None = Field(default=None, max_length=300)
    image_ids: list[str] | None = Field(
        default=None,
        description="Replacement list of Image UUID strings. Replaces the entire set.",
    )
    video_ids: list[str] | None = Field(
        default=None,
        description="Replacement list of Video UUID strings. Replaces the entire set.",
    )
